name: allure
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Report:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: Run tests
        run: npm run test
        continue-on-error: true

      - name: Generate Allure HTML report
        run: npm run report:generate

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"